version: '2'
services:
  phones-api:
    build:
      context: .
      dockerfile: ./phones.Dockerfile
    tty: true
    depends_on:
      - db
    links:
      - db
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=production
      - DB_URL=mongodb://db/masmovil
  orders-api:
    build:
      context: .
      dockerfile: ./orders.Dockerfile
    tty: true
    depends_on:
      - db
      - phones-api
    links:
      - db
      - phones-api
    ports:
      - 3001:3001
    environment:
      - NODE_ENV=production
      - USER_TOKEN=Bearer 2v1gd6u4ko
      - DB_URL=mongodb://db/masmovil
      - API_PHONES_ALL=http://phones-api:3000/phones
  db:
    image: mongo:latest
    tty: true
    ports:
      - 27017:27017
    volumes:
      - ./.data/mongo/:/data/db
